/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class MarsRover {
  constructor();
  fundAccount(account: string, balance: number): void;
  getAccount(account: string): string;
  getBalance(account: string): number;
  deployCode(accountId: string, code: Array<number>): string;
  simulateTx(transactionEnvelope: string): string;
  sendTransaction(transactionEnvelope: string): string;
  networkPassphrase(): string;
  getNetworkInfo(): string;
}
